### ISSUE TITLE
Export Ioc

### ISSUE THREAD

**Issue by DrunkenMastah** [STMicroelectronics/STM32CubeH7#106]
Currently it is a bit difficult to modify the examples as there is no ioc file and one can not open them up on CubeMx to explore , these examples would be much more useful if you exported an ioc file with them.
That is basically a feature request and not exactly an issue , do you have any thoughts about that ?

**Comment by ALABSTM** [comment]
Related to [STM32CubeL4#21](https://github.com/STMicroelectronics/STM32CubeL4/issues/21).

**Comment by ALABSTM** [comment]
Hi @DrunkenMastah,

 IOC files are published within [this](https://github.com/STMicroelectronics/STM32_open_pin_data) repository. Hopefully you will find the one(s) that would address your needs under the **./boards** directory.

With regards,

**Comment by ALABSTM** [comment]
Hi @DrunkenMastah,

Any feedback after my last comment? Could you find what you are looking for?

Thank you,

**Comment by DrunkenMastah** [comment]
Yes thank you very much ,I still believe though that a lot of useful examples (e.g. for the Discovery board) are pretty much locked for everyone using a simple gcc toolchain.
