### ISSUE TITLE
USB MSC Stack: Can't enumerate when disk is not ready

### ISSUE THREAD

**Issue by canhkha** [STMicroelectronics/STM32CubeH7#12]
**Describe the set-up**
 * The board: STM32H747I-EVAL
 * IDE: Iar 8.30

**Describe the bug**
 * Windows can't enumerate device when SD card is not ready

**How To Reproduce**
 * Suspected modules: USB Device Stack, MSC class
 * The use case that generates the problem: SD Card is not inserted
 * How we can reproduce the problem:
   * Remove sd card from sd slot
   * Run STM32Cube_FW_H7_V1.5.0\Projects\STM32H747I-EVAL\Applications\USB_Device\MSC_Standalone\EWARM\USBD_MSC.eww
   * Plug USB to Windows PC

**Additional context**
* The returning value in `int8_t SCSI_ProcessCmd(USBD_HandleTypeDef *pdev, uint8_t lun, uint8_t *cmd)` is not handled
* Ref #11 for the fix.

**Comment by ALABSTM** [comment]
Hi Canhkha,

Thank you for your message. Please allow me to introduce @bouattay from our development teams. He will analyze the issue you described and the relevance of the solution you suggested.

Please note I took the initiative to remove a couple of lines from your original description as these lines are only intended to serve as a guideline for users to state their issues. Removing them increases the readability of your message.

With regards,

**Comment by ALABSTM** [comment]
Hi Canhkha,

As already said by @bouattay, "Many changes have been added in our latest device lib v2.6.0 including a similar fix to what you have shared".

Hopefully, a new revision of the STM32CubeH7 will be published soon which will include the fix. Thank you for your patience and for your contribution once again.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 42353
