### ISSUE TITLE
Python Wrapper: cmsis_compiler.h not found (CMSIS 5.6.0)

### ISSUE THREAD

**Issue by mrest-korg** [STMicroelectronics/STM32CubeH7#120]
### Version
STM32CubeH7 v1.9.0  `(HEAD detached at v1.9.0)`

### Problem
Python CMSIS **5.6.0** DSP wrapper does not build.

### Log
```
In file included from ../Source/SupportFunctions/arm_q15_to_q31.c:29:
../Include/arm_math.h:310:10: fatal error: cmsis_compiler.h: No such file or directory
  310 | #include "cmsis_compiler.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Solution
Update CMSIS to 5.7.0

**Comment by RKOUSTM** [comment]
Hi @mrest-korg,

Thank you for your contribution. We have reported your request to our technical team, we still cannot share a date for the moment for the integration of CMSIS Core version v5.7.0. 

Please, allow me to close this issue. Thank you again for your contribution.

With regards,
