### ISSUE TITLE
MDMA Link Nodes not Double Word Aligned by CubeMX as Required

### ISSUE THREAD

**Issue by RJ-400** [STMicroelectronics/STM32CubeH7#124]
CubeMX generated code does not align MDMA linked list nodes to double word addresses as required.  This prevents MDMA from functioning when using linked list mode.

![image](https://user-images.githubusercontent.com/63032742/111852719-099be780-88e6-11eb-93e9-b68a8a2bb9cd.png)

**Comment by ALABSTM** [comment]
Hi @RJ-400,

Thank you very much for this contribution. You can report this to the Cube MX team, not through this support channel however. Indeed, this one is dedicated to aspects related to the software **published within** this repository.

Aspects like those related to ecosystem and tools are rather treated at **ST Community** level, precisely within the [Cube MX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated section in this case.

Please allow me to close this issue now. We are looking forward to reading from you.

With regards,
