### ISSUE TITLE
Missing implementation of HAL SPI master automatic SUSP in receive mode

### ISSUE THREAD

**Issue by savinz** [STMicroelectronics/STM32CubeH7#154]
Hi,

STM32H7xx_HAL_Driver defines the MasterReceiverAutoSusp configuration option in
SPI Configuration Structure definition (SPI_InitTypeDef):

    uint32_t MasterReceiverAutoSusp;

And the associated modes:

    SPI_MASTER_RX_AUTOSUSP_DISABLE
    SPI_MASTER_RX_AUTOSUSP_ENABLE

But the implementation is missing. Even if the SPI is configured with:

    ...
    phspi->Init.MasterReceiverAutoSusp = SPI_MASTER_RX_AUTOSUSP_ENABLE;
    HAL_SPI_Init(phspi);

RxFIFO can still overrun because MASRX bit is not set accordingly in hspi->Instance->CR1
by the HAL SPI driver.

Best regards,
Savin

**Comment by ASELSTM** [comment]
Hi @savinz,

Thank you your contribution. Actually, the point you raised has already been dealt and fixed internally. The fix will be made available in the frame of a future release.

We cannot share a date for the moment. So stay tuned and thank you once more for your contribution and for your patience.

With regards

**Comment by ASELSTM** [comment]
ST Internal Reference: 101564

**Comment by ASELSTM** [comment]
Hi @savinz,

Thank you for your contribution. This issue has been fixed in the frame of version v1.11.0 of the STM32CubeH7. Please allow me then to close this thread.

With regards,
