### ISSUE TITLE
Enhancement: Provide a function that is capable of storing multiple CAN messages to CAN TX FIFOs before updating TXBAR

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#157]
Hello,

I am trying to find a function that helps first find all available TX FIFOs and later fills them with (Classic) CAN Data and Extended IDs before updating a value to _hfdcan->Instance->TXBAR_. This code will be helpful to me in the long run.

There are only two functions in file _stm32h7xx_hal_fdcan.c_ that modify value of _hfdcan->Instance->TXBAR_. The two functions are namely _HAL_FDCAN_AddMessageToTxFifoQ()_ , and _HAL_FDCAN_EnableTxBufferRequest()_

_HAL_FDCAN_AddMessageToTxFifoQ()_ seems to update only one FIFO and then transmit its data.

_HAL_FDCAN_EnableTxBufferRequest()_ seems to only update _hfdcan->Instance->TXBAR_

I am unable to find a function that calls _FDCAN_CopyMessageToRAM()_ multiple times to fill the _CAN TX FIFOs_ before updating _TXBAR_

Please help implement above request.

Thanks,
@rxa1031

**Comment by rxa1031** [comment]
Hello,

Is it possible to change the _static_ typecast for _FDCAN_CopyMessageToRAM()_ and change it to just:

```void FDCAN_CopyMessageToRAM(FDCAN_HandleTypeDef *hfdcan, FDCAN_TxHeaderTypeDef *pTxHeader, uint8_t *pTxData, uint32_t BufferIndex)```

and extern it.

Please suggest.

Thanks,
@rxa1031

**Comment by rxa1031** [comment]
Hello,

As the requested code piece / function was not available, I had to code a custom / my own function for this.

May I share the coded custom function here?

Regards,
@rxa1031

**Comment by KORKAD** [comment]
Hello @rxa1031,

Thank you for your contribution. Your report will be forwarded to our development team for analyzis and if confirmed the fix will be deployed on new STM32Cube series under dev.
We will get back to you as soon as we have an answer.

Thanks in advence for your patience.

With regards,
KORKAD

**Comment by ASELSTM** [comment]
ST Internal Reference: 121056

**Comment by rxa1031** [comment]
Dear ST,

Attached is the modified CAN driver that I’ve been using.

Please refer to function CRC_Evans_FDCAN_AddMultipleMessagesToTxFifoQ() and suggest whether the implementation is correct.

Regards,
Rajeev

**Comment by HBOSTM** [comment]
Hello @rxa1031,

Thank you for this report, currently there is no plan to implement this fix, as this type of modification may create a compatibility break in the existing applications. So please allow me to close this issue. 
Thank you for your comprehension.

Best Regards,
