### ISSUE TITLE
FDCAN examples for NUCLEO-H743ZI2

### ISSUE THREAD

**Issue by sourabhmisal** [STMicroelectronics/STM32CubeH7#172]
**Set-up**
 * Board: NUCLEO-H743ZI2 (NUH743ZI$AT2)
 * IDE: STM32CubeIDE version 1.5.1
 * OS: Ubuntu 20.04 LTS

I tried using the fdcan setup from this [link](https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/STM32H743I-EVAL/Examples/FDCAN) since I did not find any demo code for my set-up board. I would like some help regarding setting up fdcan parameters as I have tried all the parameters from the example codes and tried to understand the application note ([AN5348](https://www.st.com/resource/en/application_note/dm00625700-fdcan-peripheral-on-stm32-devices-stmicroelectronics.pdf)) and apply it, but neither transmission nor reception of fdcan or can data is working. Any help would be great.

**Comment by ASELSTM** [comment]
Hi @sourabhmisal,

Please allow me to close this thread. You can reopen it at any time if you have details to provide us to help you solve this issue.
Thank you for your comprehension and thank you once more for your contribution.

With regards,
