### ISSUE TITLE
Typos in MCU header files

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/STM32CubeH7#183]
See `STM32CubeH7\Drivers\CMSIS\Device\ST\STM32H7xx\Include\*.h`
The current release 1.9.0 still contains some minor typos in MCU header files that can be easily fixed with no side-effects.

`-  HardFault_IRQn              = -13,    /*!< 4 Cortex-M Memory Management Interrupt                            */` -> `+  HardFault_IRQn              = -13,    /*!< 3 Cortex-M Hard Fault Interrupt                                   */`

`Coretx` -> `Cortex`

`Rserved` -> `Reserved`

`Busrt` -> `Burst`

**Comment by RKOUSTM** [comment]
Hi @carlo-dev-git,
 
I hope you are fine. The issue you reported has been fixed in the frame of version v1.9.1 of the STM32CubeH7 published recently on GitHub.

Thank you again for having reported.

With regards,
