### ISSUE TITLE
I2C: discrepancy between the HAL driver and the RM0433 reference manual

### ISSUE THREAD

**Issue by jeroendoggen** [STMicroelectronics/STM32CubeH7#184]
**Describe the set-up**
Discrepancy between the HAL driver and the RM0433 reference manual, no hardware needed for verification.

**Describe the bug**
The HAL driver only allows the digital and analog I2C bus filters to be configured when the I2C driver has been initialized.

Functions HAL_I2CEx_ConfigDigitalFilter() and HAL_I2CEx_ConfigAnalogFilter() in stm32h7xx_hal_i2c_ex.c can be used to configure the filters.

Both functions check the state of the driver (line 103 & 149) and only allow configuring the filter when the driver is the state HAL_I2C_STATE_READY.
The I2C peripheral is enabled by calling __HAL_I2C_ENABLE(hi2c) right before setting the core to the mentioned state. (line 569 in stm32h7xx_hal_i2c.c)

The reference manual states that the filters should be configured before the I2C peripheral is enabled (pages 1973 and 1974), and actually warns explicitly that the filters should not be changed when the I2C peripheral is enabled. A reason for this warning is not given in the reference manual though. (quote: "Caution: Changing the filter configuration is not allowed when the I2C is enabled.")

**Comment by ASELSTM** [comment]
Hi @jeroendoggen,

Please allow me to close this thread. You can reopen it at any time if you have details to provide us to help you.
Thank you for your comprehension and thank you once more for your contribution.

With regards,
