### ISSUE TITLE
STM32 HAL Timer - PWM_Config() does not reset the timer channel state.

### ISSUE THREAD

**Issue by ajitbasarur** [STMicroelectronics/STM32CubeH7#186]
**Describe the set-up**
 * STM32H7B3L evaluation board is used.
 * DRV8316R motor controller chip is used for driving a low-power BLDC motor.
 * Timer8 is configured to generate 6x PWM signals (with three of them being complimentary)

**Bug**
The function PWM_Config() does not reset the timer channel state to HAL_TIM_CHANNEL_STATE_RESET although it disables the channel.

**Describe the bug**
- STM32 HAL Timer library provides the following functions to work with PWM signals. PWM_Configure(), PWM_Start(), and PWM_Stop().
- A call to PWM_Configure() directly disables the PWM signal generation but it does not reset the timer channel state to HAL_TIM_CHANNEL_STATE_RESET. This leads to an unique usability bug.
- Let us say, we have configured a timer channel using PWM_Config() and then we have started the signal generation using PWM_Start().
- Suppose, the application wants to reconfigure the same timer channel for a different PWM settings. In this case, there are two possibilities. 
- The first possibility: Either the application will first call PWM_Stop() and then calls PWM_Config() function to change the channel settings. The channel can be started by calling PWM_Start() function.. This works perfectly fine. 
PWM_Stop() --> PWM_Config() --> PWM_Start() .. Works perfectly.
- The second possibility: Application will call PWM_Config() directly without calling PWM_Stop. Then, tries to start the PWM signal by calling PWM_Start(). This function fails because, the internal state of timer channel is not HAL_TIM_CHANNEL_STATE_RESET but it is still HAL_TIM_CHANNEL_STATE_BUSY. Therefore, PWM_Start() fails.
PWM_Config() --> PWM_Start() --> PWM_Config() --> PWM_Start() .. This fails. 

**How To Reproduce**
1. Following call sequence will reproduce the bug
**PWM_Config() --> PWM_Start() --> PWM_Config() --> PWM_Start()** .. This fails. 

**Workaround Solution**
In the application, one can explicitly check the state of each timer channel by using the following code *TIM_CHANNEL_STATE_GET(htim, Channel)*. If the timer channel state is busy, then call the PWM_Stop() function before reconfiguring the timer channel.
**PWM_Config() --> PWM_Start() --> **PWM_Stop()** --> PWM_Config() --> PWM_Start()**. This works.
This workaround should be part of the HAL Timer library.

**Proper Bug Fix**
if PWM_Config() is called, then check the status of PWM output. There are two possible implementations.
- First Implementation: Return HAL_Error. But the application might not know the real cause of failure.
- Second Implementation: Internally call PWM_Stop() and then continue with the rest of the executions within the function. This might be a reasonable approach that I would prefer as an application developer and the user of the Timer library.
STM32 can make a decision about the implementation and leave a response in the reply section.

Best Regards,
Ajit B

**Comment by ASELSTM** [comment]
Hi @ajitbasarur,

The **PWM_Stop()** is necessary to ensure a correct system behavior. Indeed, the configuration can't be updated since the channel is activated. Changes on the fly are not allowed unless the channel is stopped. The driver has been implemented in the way to respect this sequencing. Control and configuration are separately managed to avoid any system misbehavior. 
Hence, the correct sequence to deploy is :

`PWM_Config() --> PWM_Start() --> PWM_Stop() --> PWM_Config() --> PWM_Start() ...`

Unfortunately, you request can't be accepted, so please allow me to close this thread. Thank you for you comprehension.

With regards,
