### ISSUE TITLE
Error on include.

### ISSUE THREAD

**Issue by georthom** [STMicroelectronics/STM32CubeH7#188]
https://github.com/STMicroelectronics/STM32CubeH7/blob/5975bffae9358bc2b2890a35a203d940a395efef/Drivers/BSP/STM32H743I-EVAL/stm32h743i_eval_lcd.h#L32

Shouldn't it be :
#include "stm32h743i_eval_conf_template.h"   ?

**Comment by ALABSTM** [comment]
Hi @georthom,

This is `#include "stm32h743i_eval_conf.h"` indeed. Actually, `*_template.h` files are generic files that are intended to be:
* **Copied** into your projects file tree.
* **Renamed** by removing the `template` suffix.
* **Customized** according to the needs of your application.

For instance, you can notice how this same file has been customized differently for two different applications.

https://github.com/STMicroelectronics/STM32CubeH7/blob/5975bffae9358bc2b2890a35a203d940a395efef/Projects/STM32H743I-EVAL/Applications/Audio/Audio_playback_and_record/Inc/stm32h743i_eval_conf.h#L31-L33

https://github.com/STMicroelectronics/STM32CubeH7/blob/5975bffae9358bc2b2890a35a203d940a395efef/Projects/STM32H743I-EVAL/Applications/Display/LTDC_PicturesFromSDCard/Inc/stm32h743i_eval_conf.h#L31-L33

I hope this point is clearer now. Please allow me to close this issue.

With regards,
