### ISSUE TITLE
Flash Dual bank for H735 and H725

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/STM32CubeH7#202]
In [this ST document](https://www.st.com/content/ccc/resource/training/technical/product_training/group0/1f/4f/b7/85/91/e0/4d/2f/STM32H7-Memory-Flash_FLASH/files/STM32H7-Memory-Flash_FLASH.pdf/_jcr_content/translations/en.STM32H7-Memory-Flash_FLASH.pdf) I read that

> STM32H7 devices embed high-speed embedded memories with a dual-bank Flash memory up to 2 Mbytes that can be used for storing programs and data.
> ...
> The STM32H7 series has a Flash memory with Dual-bank organization supporting simultaneous operations: two read/program/erase operations can be executed in parallel on the two banks.

But in [stm32h725xx.h](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h725xx.h) and [stm32h735xx.h](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h735xx.h) I see only definition for BANK1
`#define FLASH_BANK1_BASE ....`

Are BANK2 defines missing?

**Comment by RKOUSTM** [comment]
Hi @escherstair,

Thank you for this report. Indeed, [this](https://www.st.com/content/ccc/resource/training/technical/product_training/group0/1f/4f/b7/85/91/e0/4d/2f/STM32H7-Memory-Flash_FLASH/files/STM32H7-Memory-Flash_FLASH.pdf/_jcr_content/translations/en.STM32H7-Memory-Flash_FLASH.pdf) ST document is not updated and does not include all details about STM32H7 Flash memory interface. So please refer to the datasheet of [STM32H725xE/G](https://www.st.com/content/ccc/resource/technical/document/datasheet/group3/0a/b4/c7/86/2d/9b/4e/d7/DM00701017/files/DM00701017.pdf/jcr:content/translations/en.DM00701017.pdf) and [STM32H735xG](https://www.st.com/content/ccc/resource/technical/document/datasheet/group3/4d/cb/39/b8/71/06/40/56/DM00701023/files/DM00701023.pdf/jcr:content/translations/en.DM00701023.pdf) on st.com site where they are characterized by up to 1 Mbyte Flash memory . 

Regarding the point for which you opened the issue, as it is irrelevant, allow me to close the issue. Thank you for your comprehension and thank you again for your report.

With regards,
