### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by howroyd** [STMicroelectronics/STM32CubeH7#223]
The below link takes me to a 404 page:

https://github.com/STMicroelectronics/STM32CubeH7/blob/0c3a06c18bd2a87b006a84f997f2b0b56d97a113/Middlewares/ST/STM32_Audio/Addons/PDM/readme.txt#L16

I am still looking for the files so if there is an updated link that would be great please.

**Comment by ASELSTM** [comment]
Hi @howroyd,

Thank you for having reported this point. Indeed, we are experiencing some issues with these links. We recommend to download the full zipped package from [st.com](https://www.st.com/en/embedded-software/stm32cubeh7.html) as a workaround.

With regards,

**Comment by ASELSTM** [comment]
Hi
