### ISSUE TITLE
Bug in older SCB_DisableDCache() implementation

### ISSUE THREAD

**Issue by Irisbus** [STMicroelectronics/STM32CubeH7#226]
**Describe the set-up**
 * Issue exhibited on our custom board with STM32H735 MCU
 * IDE version: STM32CubeIDE v1.10.0 IDE

**Describe the bug**
There was a buggy implementation of `SCB_DisableDCache()` function in the CMSIS driver package. It was repaired few days ago in [this](https://github.com/ARM-software/CMSIS_5/commit/36bd54f7963825954b3dd37c036dbbcd1494988f) commit. I've encountered this issue: when the function `SCB_DisableDCache()` is called, it may sometimes result in an endless loop with ending clause at [this](https://github.com/STMicroelectronics/STM32CubeH7/blob/0c3a06c18bd2a87b006a84f997f2b0b56d97a113/Drivers/CMSIS/Include/core_cm7.h#L2391) line, due to some cache inconsistency.

**How To Reproduce**
Calling `SCB_DisableDCache()` function before jumping to bootloader caused this issue. MCU enters endless loop. When I tried to use the function copied from [here](https://github.com/ARM-software/CMSIS_5/blob/36bd54f7963825954b3dd37c036dbbcd1494988f/CMSIS/Core/Include/cachel1_armv7.h#L181), it worked as expected.

**Additional context**
[Link](https://community.st.com/s/question/0D53W00000oVveoSAC/problems-using-the-cache-and-scbdisabledcache-in-bootloader-before-jumping-to-application) to relevant question from the ST's forum.

**Screenshots**
N/A

**Comment by ALABSTM** [comment]
Fixed in commit [ARM-software/CMSIS_5#36bd54f796](https://github.com/ARM-software/CMSIS_5/commit/36bd54f7963825954b3dd37c036dbbcd1494988f). Waiting for **official tag** from Arm to integrate it into STM32H7Cube firmware.
