### ISSUE TITLE
NUCLEO-H745ZI-Q Ethernet example needed

### ISSUE THREAD

**Issue by Ali-Mirghasemi** [STMicroelectronics/STM32CubeH7#233]
I'm trying use `NUCLEO-H745ZI-Q` Ethernet part but i couldn't even ping board

## Hardware
i did test my projects on two different hardware, both in RMII mode
- Board: NUCLEO-H745ZI-Q
- MCU: STM32H743ZI

## Tutorial Tested
- [ST Guide line](https://community.st.com/s/article/How-to-create-project-for-STM32H7-with-Ethernet-and-LwIP-stack-working)
- [Third-party Guide](https://controllerstech.com/stm32-ethernet-1-connection/)
- ST H743 Examples

i did follow all these guides but no improve in getting at least 1 ping

i think it's good to have Ethernet example for `NUCLEO-H745ZI-Q` board

**Comment by TOUNSTM** [comment]
Hello @Ali-Mirghasemi,

First we would like to thank you for your report. You can find a simple Ethernet examples based on LwIP and FreeRTOS, running on NUCLEO-H745ZI-Q board here:

- [STM32H745_Nucleo_M4_ETH](https://github.com/stm32-hotspot/STM32H7-LwIP-Examples/tree/main/STM32H745_Nucleo_M4_ETH)
- [STM32H745_Nucleo_M7_ETH](https://github.com/stm32-hotspot/STM32H7-LwIP-Examples/tree/main/STM32H745_Nucleo_M7_ETH)

However, there is no plan to add examples in the  the **STM32CubeH7 firmware**. Please allow me to close this issue now. Thank you again for your contribution. 

With regards,
