### ISSUE TITLE
Linker script issue

### ISSUE THREAD

**Issue by smdjeff** [STMicroelectronics/STM32CubeH7#235]
https://github.com/STMicroelectronics/STM32CubeH7/blob/4cb7c570fa5f2a362193d713a70b43ab02c68197/Projects/STM32H735G-DK/Applications/LwIP/LwIP_TCP_Echo_Server/STM32CubeIDE/STM32H735IGKX_FLASH.ld#L41

Pretty sure there's only 32k here not 288k.
Also, you're leaving about 320k on the table at 0x24000000

**Comment by smdjeff** [comment]
Complete and correct linker scripts for all parts would be super handy to developers.

**Comment by ASELSTM** [comment]
ST Internal Reference: 152716

**Comment by ALABSTM** [comment]
Hi @smdjeff,

I hope you are fine. Please excuse the time taken to get back to you. The fix has just been uploaded. Thank you again for having reported.

With regards,

**Comment by ALABSTM** [comment]
Fixed in commit c8c46c579b90011af4bf5e0c18ccf8a324c8e01c
