### ISSUE TITLE
SAI_AudioPlayback on h745 Discovery Board with Keil Armclang

### ISSUE THREAD

**Issue by axbusch** [STMicroelectronics/STM32CubeH7#242]
STM32H745i Discovery Board
Keil 5.37 with Armclang 6.18

I tried the example with the old Keil armcc Compiler and the example works fine.
Then i switched to armclang compiler and replaced the "libPDMFilter_cm7_keil_wc16.lib" with the provided "libPDMFilter_cm7_gcc_wc16.a"
Everything compiles & runs fine except the fact that the output of the lib in audioPcmBuf[] is always zero

is there something special i have to configure to make this lib work? i can remember in the past there were similar problems with touch gfx and the armclang compiler but these were solved eventually.

DebugScreenshots are in this thread
https://community.st.com/t5/other-solutions-mcu/sai-audioplayback-example-with-armclang/td-p/112464

**Comment by ALABSTM** [comment]
Hi @axbusch,

I see from your last [comment](https://community.st.com/t5/stm32-mcus-other-solutions/sai-audioplayback-example-with-armclang/m-p/588814/highlight/true#M3175) on the community that you solved this problem. Please allow me to close this issue. Thank you for your comprehension.

With regards,
