### ISSUE TITLE
Closing brace of ifdef cplusplus is missing in NUCLEO-H723ZG example: USB_Host/HID_Standalone/USB_Host/Target/usbh_conf.h

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32CubeH7#269]
https://github.com/STMicroelectronics/STM32CubeH7/blob/af967c5899d8f5c11eff4a12d647d11b823986a4/Projects/NUCLEO-H723ZG/Applications/USB_Host/HID_Standalone/USB_Host/Target/usbh_conf.h#L90

Results in non-building example.

Found by a customer, ref: https://community.st.com/t5/stm32cubeide-mcu/how-to-convert-a-c-project-into-c-project/td-p/578997

**Comment by ALABSTM** [comment]
Hi @pavel-a,

Thank you for having reported. It will be forwarded to our development teams.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 159302

**Comment by ALABSTM** [comment]
Fixed in commit 9788a459a431616c65165cbdc809abe287c13321
