### ISSUE TITLE
"BSP" example for STM32H747I-DISCO is missing in the repo

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32CubeH7#276]
The "BSP" example for STM32H747I-DISCO is available in downloadable CubeH7 package, but missing in this repo:

Projects/STM32H747I-DISCO/Examples/BSP

May apply to other H7 boards examples  too.

**Comment by RJMSTM** [comment]
Hello @pavel-a,

MW libraries subject to click-thru have been already removed from this repo along with the projects using them. 
The "BSP" example for STM32H747I-DISCO you have mentioned is one of these examples.
you can refer to [this](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/17) post for more details.

With Regards,
Rania
