### ISSUE TITLE
Missing WIFI, Clock, and Weather Examples in Latest Update

### ISSUE THREAD

**Issue by bnina-ayoub** [STMicroelectronics/STM32CubeH7#285]
Hello,

I recently updated my firmware and noticed that the WIFI, Clock, and Weather examples, which were previously available, are now missing from the latest update of the STM32H7 repository.

The old WIFI connection code, which was extracted from the Clock and Weather examples, is no longer working after the firmware update. This has caused some disruption in my project development.

Could you please look into this issue? It would be greatly appreciated if these examples could be reintroduced or if updated versions could be provided.

**Comment by ALABSTM** [comment]
Hi @bnina-ayoub,

Sorry to read this disrupted your project, but these examples, along with others have been **removed** as they use some middleware libraries that are **not** published on GitHub.

Please refer to [this](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/README.md#some-middleware-libraries-and-projects-are-unavailable-in-this-repository) section in the `README.md` for further details. As explained there, you will need to download the firmware from [st.com](https://www.st.com/en/embedded-software/stm32cubeh7.html#get-software), in case you need those examples.

With regards,
