### ISSUE TITLE
register storage class specifier is deprecated in C++17

### ISSUE THREAD

**Issue by Mathullah** [STMicroelectronics/STM32CubeH7#288]
GCC compailer throws an error after update to latestest firmware package. 

**Describe the set-up**
Use firmware package STM32Cube_FW_H7_V1.11.2

**Additional context**
Remove deprecated keyword _register_

**Screenshots**
https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/db7e4a987cc58023a53a255f8617f6e3fb76731b/Inc/stm32h7xx_ll_dma.h#L1620

**Comment by Mathullah** [comment]
Same topic as #15

**Comment by ALABSTM** [comment]
Hi @Mathullah,

Seems this one has slipped through the cracks. Thank you for the heads-up. It will be fixed soon hopefully.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 180958

**Comment by TOUNSTM** [comment]
Fixed in 8addbb7d433deab490c0c8cbe17a7cab81bbe5b0
