### ISSUE TITLE
STM32H747 SWD can not connect anymore

### ISSUE THREAD

**Issue by guadiandehao** [STMicroelectronics/STM32CubeH7#297]
About the board:
We referenced to portenta h7 board to build a board.

About the firmare:
We are using STM32Cube FW_H7 v1.11.2 and add a toggle GPIO in while(1) and relevant gpio initalize code.

If programed the STM32H747, then i can't connect to the device anymore. I tried this [link](https://community.st.com/t5/stm32-mcus/unable-to-connect-to-stm32h7-devices/ta-p/49296)method, but not working. Is there anything i missed?

**Comment by ALABSTM** [comment]
Hi @guadiandehao,

As indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/CONTRIBUTING.md#3-support-requests-and-questions) file, this support channel is specially dedicated to issues directly related to the software provided within this repository.

Support requests like yours should rather be submitted to the [ST Community](https://community.st.com/t5/product-forums/ct-p/product-forums). There, you should find the support you are looking for.

Please allow me to close this thread. Thank you for your comprehension and best of luck with your project.

With regards,
