### ISSUE TITLE
Spelling: "secion" instead of "section" in >900 places

### ISSUE THREAD

**Issue by thomask77** [STMicroelectronics/STM32CubeH7#35]
"section" has been misspelled as "secion" in a lot of places (just grep for it :))

One example:

https://github.com/STMicroelectronics/STM32CubeH7/blob/3d3ffbe6e15fc7e4d8a4d275e9fb3a334e31c8a3/Projects/STM32H750B-DK/Examples/MDMA/MDMA_LinkedList/SW4STM32/STM32H750B-DISCO/STM32H750XBHx_FLASH.ld#L142

**Comment by ALABSTM** [comment]
Duplicate of #37.
