### ISSUE TITLE
Spelling: "intitialization" instead of "initialization" in >800 places

### ISSUE THREAD

**Issue by thomask77** [STMicroelectronics/STM32CubeH7#36]
Just grep for it..

One example:

https://github.com/STMicroelectronics/STM32CubeH7/blob/e261d820b398846a94f22f4aeb32d86c29546efb/Drivers/CMSIS/docs/Core/html/system_c_pg.html#L163

**Comment by ALABSTM** [comment]
Duplicate of #37.
