### ISSUE TITLE
Obsolete Keil pack for H7

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32CubeH7#4]
This file can be removed from the repo. Newer pack v. 2.3 is already released online.

https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Utilities/PC_Software/IDEs_Patches/MDK-ARM/Keil.STM32H7xx_DFP.2.2.1.zip

For large binary files please consider LFS.

Regards,
-- pavel a.

**Comment by ALABSTM** [comment]
Hi Pavel,

Thank you for pointing out this detail. We already submitted your request to our "Tools" team. We will be back to you as soon as we have an answer.

With regards,
