### ISSUE TITLE
Missing CMakeLists

### ISSUE THREAD

**Issue by WBABD** [STMicroelectronics/STM32CubeH7#40]
- Please can you add a CMakeLists for this project. At the moment all of my projects have to create a CMakeLists for the HAL whereas I think it should be added into the library as it's very much the standard for C/C++ projects.

**Comment by ALABSTM** [comment]
Hi @WBABD,

Thank you for having tackled this aspect. You request has been forwarded to our development teams. We will be back to you as soon as they provide us with their answers.

With regards,

**Comment by ALABSTM** [comment]
Hi @WBABD,

I hope you are doing well. Excuse this late answer. Unfortunately, we do not provide `CMakeLists.txt` files within our firmware packages. However, you can find several initiatives from **STM32** users providing such files. You can, for instance, check the [stm32-cmake](https://github.com/ObKo/stm32-cmake) project.

I hope this helps. Please allow me to close this issue now.

With regards,
