### ISSUE TITLE
Use BSP_SD_ReadBlocks_DMA() fail, SDMMC1_IRQHandler() interrupt cannot occur

### ISSUE THREAD

**Issue by ACFLY-FlightControl** [STMicroelectronics/STM32CubeH7#53]
usb_device MSC project   st driver version 1.9.0

st sd card driver,Use BSP_SD_ReadBlocks_DMA() fail, SDMMC1_IRQHandler() interrupt cannot occur!!!

Use the non dma mode is working.

the sram is Axi-sram,non-cacheable,4 byte anlign.

what's strange is fatfs sd card working with dma mode!!!  Same driver!!!  Same Board!!!

Debug shows no sdmmc1 error,SDMMC1 just cannot occur！！！

**Comment by ALABSTM** [comment]
Hi @Thanos-Love-Ironman,

Thank you for your report. It has been forwarded to our development teams. Just for confirmation, you are using the **USB Device** [MSC_Standalone](https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/STM32H743I-EVAL/Applications/USB_Device/MSC_Standalone) application of the STM32H743I-EVAL board. Aren't you?

With regards,

**Comment by ALABSTM** [comment]
Hi @ACFLY-FlightControl,

Any update regarding this issue? Still facing it? Would you mind checking whether it is related to [STM32CubeL4#28](https://github.com/STMicroelectronics/STM32CubeL4/issues/28)?

With regards,

**Comment by ALABSTM** [comment]
Hi @ACFLY-FlightControl,

I hope you are fine. Please allow me to close this issue as no reply has been received since a couple of months. Do not hesitate to reopen it in case you think the point is still relevant.

With regards,
