### ISSUE TITLE
Functions like osAbortDelay(), osMessageWaiting() wrappers unavailable in file cmsis_os2.c

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#73]
Hello,

I was looking out for a CMSIS wrapper for FreeRTOS function xTaskAbortDelay() and found that the wrapper is only available with CMSIS_OS.C.

`As I am using FreeRTOS with CMSIS Version 2 the wrapper is not available for use.` The reason for this is that CMSIS_OS2.C (and CMSIS_OS2.H) do not implement the wrapper function.

_May ST please add the necessary wrapper functions that are available in CMSIS_OS.C to CMSIS_OS2.C file as well._

Thanks,
Rajeev

**Comment by ASELSTM** [comment]
Hi @rxa1031,

Thank you for your report. It has been forwarded to our development teams. We will get back to you as soon as they provide us with their feedback.

Best regards,

**Comment by rxa1031** [comment]
Hello @ALABSTM ,

Are there any findings / updates that you may be able to share with me.

Thanks,
Rajeev

**Comment by RKOUSTM** [comment]
Hi @rxa1031,

I hope you are fine. Our development teams said your proposal could not be taken into consideration for the following reason:

> CMSIS_RTOS is not meant to cover every single API from every RTOS. When a feature is needed for a specific use case, a user can add its macro in the application code. On CMSIS_RTOS_V1 implemented the osAbortDelay and then in CMSIS_RTOS_V2 this choice has not been continued in order to keep the interface as simple and as generic as possible.

We really wished to provide you with a positive answer, but could unfortunately not. Please allow me to close this issue now and thank you for your comprehension.

With regards,

**Comment by ALABSTM** [comment]
See also [STM32CubeF4#170](https://github.com/STMicroelectronics/STM32CubeF4/issues/170)
