### ISSUE TITLE
incorrect implementation of pvPortMalloc by the heap_4.c of FreeRTOS

### ISSUE THREAD

**Issue by TheSilentDawn** [STMicroelectronics/STM32CubeH7#85]
**Describe the set-up**
 * Development board: STM32H7B3I-DK and STM32H7B3I-EVAL
 * IDE and version: STMCubeIDE 1.4.0

**Describe the bug**
The function pvPortMalloc() is used to allocate memory for the required size.
The parameter xWantedSize indicates the length of memory required. However, when the required memory block size is zero. The memory pointer variable pvReturn will keep as NULL. If the configuration configUSE_MALLOC_FAILED_HOOK is enabled, it will recognize the variable xWantedSize valued zero as an error and handle it with the function vApplicationMallocFailedHook() as shown in https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5fb26de0194b4ebfd09b37128bf9f3ff6d34c1b7/portable/MemMang/heap_4.c#L253 (also https://github.com/STMicroelectronics/STM32CubeH7/blob/beced99ac090fece04d1e0eb6648b8075e156c6c/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c#L249)

**How To Reproduce**
1. Import the Domenstration example ClockAndWeather of the board STM32H7B3I-DK.

2. Enable macro configUSE_MALLOC_FAILED_HOOK. This is default enabled when I try to debug the program.

3. Run the firmware with a default configuration to reproduce and it will loop infinitely.

4. This problem is caused by the incorrect implementation of the function pvPortMalloc() by heap_4.c of FreeRTOS. This bug is already reported to FreeRTOS as shown in https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/204. 

**Additional context**

To patch it, should return NULL or the next available heap address when the parameter xWantedSize is zero.

**Comment by RKOUSTM** [comment]
Hi @TheSilentDawn,

Thank you for this report. Unfortunately, for this point, we don't treat aspect related to FreeRTOS in our GitHub repositories. As the ``heap_4.c`` file is out of the scope of STMicroelectronics, any modifications concerning this file are not implemented by our technical team. 

Please allow me to close this issue now. Thank you for your contribution. 

With regards,
