### ISSUE TITLE
null pointer dereference of lwip function ip_reass_free_complete_datagram

### ISSUE THREAD

**Issue by TheSilentDawn** [STMicroelectronics/STM32CubeH7#92]
**Describe the set-up**
 * The board: STM32H7B3I-DK
 * IDE: STM32CubeIDE 1.4.0
 * Projects: stm_udp_echo_server, stm_udp_echo_client, stm_tcp_echo_server, stm_tcp_echo_client

**Describe the bug**
The lwip function ip_reass_free_complete_datagram() is used to free a datagram (struct ip_reassdata) and all its pbufs. It's called by the function ip_reass_tmr() timely or the function ip_reass_remove_oldest_datagram() to clear oldest datagram.

When trying to build _struct ip_reass_helper *iprh_, then function ip_reass_free_complete_datagram() dereference the pointer _ipr->p->payload_ as below. 
https://github.com/STMicroelectronics/STM32CubeH7/blob/beced99ac090fece04d1e0eb6648b8075e156c6c/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c#L178. 
However, it doesn't check if _ipr->p_ is a null pointer and there is a chance it could be. This will lead to a null pointer dereference bug.  

**How To Reproduce**
1. Run the demo stm_udp_echo_client which includes lwip.

2. Here is a test case which is a pcap structure package that could be used to reproduce the problem.

[testcase0.txt](https://github.com/STMicroelectronics/STM32CubeH7/files/5550488/testcase0.txt)

**Additional context**
1. To patch it, lwip should check if _ipr->p_ is null firstly.
2. This bug still exists in the latest lwip, we have reported it to lwip too.

**Comment by RKOUSTM** [comment]
Hi @TheSilentDawn,

Thank you for this report. Unfortunately we don't treat aspect related to Third_Party files in our GitHub repositories. As these files are out of the scope of STMicroelectronics, any modifications concerning ``ip4_frag.c`` file are not implemented by our technical team.

Please allow me to close this issue now. Thank you again for your contribution.
 
With regards,
