### ISSUE TITLE
Requesting code integration / update to use FreeRTOS version 10.4.0

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/STM32CubeH7#97]
Hello,

May you please help with code integrating / update to use the FreeRTOS version 10.4.0 which has got additional features.

Thanks,
Rajeev

**Comment by RKOUSTM** [comment]
Hi @rxa1031,

Thank you for your contribution. We have reported your request to our technical team, we still cannot share a date for the moment for the integration of ``FreeRTOS`` version ``v10.4.0``. We will keep you informed.

Thank you again for your contribution.

With regards,
